### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by chancefeick**
Merge 2.0 branch into master. Includes the following PRs:

* [#117](https://github.com/librato/librato-metrics/pull/117): Remove support for deprecated methods
* [#118](https://github.com/librato/librato-metrics/pull/118): Upgrade rspec
* [#119](https://github.com/librato/librato-metrics/pull/119): Remove support for ruby 1.8

Roadmap: https://github.com/librato/librato-metrics/issues/110

### CODE REVIEW

**Comment by chancefeick** [comment]
Will originally cut this as `2.0.0.beta`.

**Comment by chancefeick** [comment]
Verified unit and integration tests passing locally:

```
Finished in 4.42 seconds (files took 0.25375 seconds to load)
98 examples, 0 failures

Finished in 4.69 seconds (files took 0.25611 seconds to load)
53 examples, 0 failures
```

**Comment by nextmat** [comment]
Awesome, this also includes dropping multijson as a hard dependency, now it is only used if already required (otherwise we use stdlib json).

This LGTM :+1:

**Comment by chancefeick** [comment]
Thanks for the reminder. Added to CHANGELOG in eeebc29bdbb7658383c04d95fa9102f602dce431.

**Comment by chancefeick** [comment]
Following up: `2.0.0.beta` has been stable for a month, going to promote to `2.0.0`.

**Pull request merged**
